
server:
  port: 9601

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/x_mind?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: XmindInsight
        password: password
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.winter.model